apiVersion: apps/v1
kind: Deployment
metadata:
  name: financeme-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: financeme
  template:
    metadata:
      labels:
        app: financeme
    spec:
      containers:
        - name: financeme-container
          image: akhilbmenon/staragile-financeme:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: financeme-service
spec:
  type: NodePort
  selector:
    app: financeme
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30037
